host: 0.0.0.0
port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 60000
# define the interval used by Mozaïk Bus to call registered APIs
apisPollInterval: 100000

dashboards:
  - columns: 3
    rows:    3
    widgets:
      - type:       mozaik.inspector
        user:       plouc
        columns:    1
        rows:       1
        x:          0
        y:          0

      - type:       github.user_badge
        user:       plouc
        columns:    1
        rows:       1
        x:          1
        y:          0

      - type:       github.repository_contributors_stats
        repository: plouc/mozaik
        columns:    1
        rows:       1
        x:          2
        y:          0

      - type:       github.status
        columns:    1
        rows:       1
        x:          0
        y:          1

      - type:       github.branches
        repository: plouc/mozaik
        columns:    1
        rows:       1
        x:          1
        y:          1

      - type:       github.pull_requests
        repository: plouc/mozaik
        columns:    1
        rows:       1
        x:          2
        y:          1

      - type:       github.issue_labels_donut
        repository: plouc/mozaik
        columns:    2
        rows:       1
        x:          0
        y:          2

      - type:       travis.build_history
        owner:      plouc
        repository: mozaik
        columns:    1
        rows:       1
        x:          2
        y:          2